const STORAGE_KEY='nymia-home-v2';
const defaultState={onboardingComplete:false,profile:{firstName:'',birthDate:'',goals:[]},notificationChoice:'not-asked',items:[],metrics:{sleep:'',water:'',activity:''},chat:[],focusDismissed:false};
let state=loadState(),step=0,currentPage='home';
const app=document.querySelector('#app'),toastEl=document.querySelector('#toast');
function loadState(){try{return {...structuredClone(defaultState),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return structuredClone(defaultState)}}function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(m){toastEl.textContent=m;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1700)}
function progress(){return `<div class="progress">${[0,1,2,3,4].map(i=>`<span class="${i<=step?'active':''}"></span>`).join('')}</div>`}function layout(c,b=''){return `<main class="onboarding">${progress()}<div class="brand">Nymia</div><section class="hero">${c}</section><div class="actions">${b}</div></main>`}
function welcome(){return layout(`<div class="hero-visual"><img src="hummingbird-clean.png"></div><h1>Ta santé, enfin organisée simplement.</h1><p class="lead">Crée ton espace et remplis-le progressivement avec tes propres informations.</p>`,`<button class="primary" data-next>Commencer</button>`)}function features(){return layout(`<h1>Tout au même endroit</h1><p class="lead">Santé, bien-être, documents et rappels.</p><div class="feature-list"><div class="feature"><div class="feature-icon">🩺</div><div><b>Suivi santé</b><small>Traitements et rendez-vous.</small></div></div><div class="feature"><div class="feature-icon">🌿</div><div><b>Bien-être</b><small>Sommeil, hydratation et activité.</small></div></div><div class="feature"><div class="feature-icon">🔒</div><div><b>Données privées</b><small>Conservées sur cet appareil.</small></div></div></div>`,`<button class="primary" data-next>Continuer</button><button class="ghost" data-back>Retour</button>`)}function profile(){return layout(`<h1>Faisons connaissance</h1><div class="form-wrap"><label class="label">Prénom</label><input class="input" id="firstName" value="${esc(state.profile.firstName)}" placeholder="Ton prénom"><label class="label">Date de naissance (facultatif)</label><input class="input" id="birthDate" type="date" value="${esc(state.profile.birthDate)}"></div>`,`<button class="primary" data-save-profile>Continuer</button><button class="ghost" data-back>Retour</button>`)}const goalOptions=[['health','🩺','Organiser ma santé'],['wellbeing','🌿','Suivre mon bien-être'],['documents','📄','Centraliser mes documents'],['reminders','🔔','Recevoir des rappels']];function goals(){return layout(`<h1>Que veux-tu suivre ?</h1><div class="choices">${goalOptions.map(([id,ic,l])=>`<button class="choice ${state.profile.goals.includes(id)?'selected':''}" data-goal="${id}"><span>${ic}</span><b>${l}</b></button>`).join('')}</div>`,`<button class="primary" data-save-goals>Continuer</button><button class="ghost" data-back>Retour</button>`)}function notifications(){return layout(`<h1>Rester informée</h1><div class="permission-card"><div class="row"><div class="bell">🔔</div><div><b>Notifications Nymia</b><p>Tu gardes le contrôle.</p></div></div><div class="permission-status">Tu pourras modifier ce choix plus tard.</div></div>`,`<button class="primary" data-enable-notifications>Autoriser</button><button class="secondary" data-finish>Plus tard</button><button class="ghost" data-back>Retour</button>`)}function onboarding(){app.innerHTML=[welcome,features,profile,goals,notifications][step]();bindOnboarding()}
function bindOnboarding(){const next=document.querySelector('[data-next]');if(next)next.onclick=()=>{step++;onboarding()};const back=document.querySelector('[data-back]');if(back)back.onclick=()=>{step=Math.max(0,step-1);onboarding()};const saveProfile=document.querySelector('[data-save-profile]');if(saveProfile)saveProfile.onclick=()=>{const n=document.querySelector('#firstName').value.trim();if(!n)return toast('Entre ton prénom');state.profile.firstName=n;state.profile.birthDate=document.querySelector('#birthDate').value;save();step++;onboarding()};document.querySelectorAll('[data-goal]').forEach(b=>b.onclick=()=>{const id=b.dataset.goal;state.profile.goals=state.profile.goals.includes(id)?state.profile.goals.filter(x=>x!==id):[...state.profile.goals,id];save();onboarding()});const saveGoals=document.querySelector('[data-save-goals]');if(saveGoals)saveGoals.onclick=()=>{if(!state.profile.goals.length)return toast('Choisis au moins un objectif');step++;onboarding()};const enableNotifications=document.querySelector('[data-enable-notifications]');if(enableNotifications)enableNotifications.onclick=async()=>{try{state.notificationChoice=('Notification' in window)?await Notification.requestPermission():'unsupported'}catch{state.notificationChoice='unsupported'}save();finishOnboarding()};const finish=document.querySelector('[data-finish]');if(finish)finish.onclick=finishOnboarding}
function finishOnboarding(){state.onboardingComplete=true;save();renderShell('home')}
function todayLabel(){return new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).replace(/^./,c=>c.toUpperCase())}
const typeMeta={symptom:['💗','Symptôme'],treatment:['💊','Traitement'],note:['📝','Note'],document:['📜','Document'],meal:['🥣','Repas'],appointment:['🗓️','Rendez-vous']};
function home(){const items=[...state.items].sort((a,b)=>(a.time||'99:99').localeCompare(b.time||'99:99'));return `<header class="home-header"><div class="hello"><h1>Bonjour, ${esc(state.profile.firstName||'toi')} 👋</h1><div class="date">${todayLabel()}</div><div class="mood">💗 Passe une belle journée 🌸</div></div><div class="header-actions"><button class="bell-btn" data-notifications>♧</button><button class="profile-avatar" data-page="profile">${esc((state.profile.firstName||'N')[0].toUpperCase())}</button></div></header><section class="home-screen">${state.focusDismissed?'':`<article class="focus-card"><button class="focus-close" data-dismiss-focus>×</button><img class="focus-art" src="hummingbird-clean.png" alt="Colibri"><div class="focus-content"><div class="focus-label"><span>★</span> FOCUS DU JOUR</div><h2>${items.length?'Ton programme est prêt.':'Commence ton premier suivi aujourd’hui.'}</h2><p>${items.length?'Retrouve tes prochains éléments dans la section Aujourd’hui.':'Ajoute une première information pour personnaliser ton accueil.'}</p></div><div class="focus-buttons"><button class="filled" data-add="appointment">${items.length?'Voir aujourd’hui':'Commencer'}</button><button class="outline" data-page="health">En savoir plus</button></div></article>`}<article class="colibri-card"><div class="colibri-top"><div class="colibri-icon"><img src="hummingbird-clean.png"></div><div class="colibri-copy"><div class="colibri-title">Colibri <span class="beta">BETA</span></div><p>Je suis là si tu as une question ou besoin d’aide.</p></div><button class="chev" data-page="colibri">›</button></div><div class="ask-row"><input id="askColibri" placeholder="Pose-moi une question..."><button data-send-colibri>✦</button></div></article><div class="section-head"><h3>🗓 AUJOURD’HUI</h3><button data-page="health">Voir tout ›</button></div>${items.length?`<div class="today-list">${items.slice(0,4).map(i=>`<button class="today-row" data-item="${i.id}"><div class="time-pill">${esc(i.time||'—')}</div><div><b>${typeMeta[i.type][0]} ${esc(i.title)}</b><small>${esc(typeMeta[i.type][1])}</small></div><span>›</span></button>`).join('')}</div>`:`<div class="today-empty"><div class="cal">🗓️</div><span>Aucun événement aujourd’hui</span></div>`}<div class="section-head"><h3>⚡ ACTIONS RAPIDES</h3><button data-customize>Personnaliser ›</button></div><div class="quick-actions">${Object.entries(typeMeta).map(([id,[ic,label]])=>`<button class="quick-action" data-add="${id}"><div class="iconbox">${ic}</div><small>${label}</small></button>`).join('')}</div><div class="section-head"><h3>📈 MON ÉVOLUTION</h3><button data-page="wellbeing">Voir plus ›</button></div><div class="evolution-grid">${metric('sleep','🌙 Sommeil',state.metrics.sleep||'Aucune donnée','sleep')}${metric('water','💧 Hydratation',state.metrics.water||'Aucune donnée','water')}${metric('activity','🏃 Activité',state.metrics.activity||'Aucune donnée','activity')}</div></section>`}
function metric(id,title,value,cls){return `<button class="metric-card ${cls}" data-metric="${id}" style="text-align:left"><div class="metric-title">${title}</div><div class="metric-value">${esc(value)}</div><div class="metric-note">Appuie pour renseigner</div><svg class="spark" viewBox="0 0 120 35" preserveAspectRatio="none"><polyline points="0,26 15,30 29,28 43,17 58,20 71,15 87,19 104,12 120,8"/></svg></button>`}
function healthPage(){const groups=['treatment','appointment','symptom','document','note','meal'];return `<section class="module-page"><div class="page-title"><div><h2>Ma santé</h2><p>Retrouve les informations ajoutées depuis l’accueil.</p></div><button class="page-add" data-open-add>+</button></div><div class="health-grid">${groups.map(type=>{const list=state.items.filter(i=>i.type===type);const [ic,label]=typeMeta[type];return `<article class="health-card"><div class="health-card-head"><span class="health-icon">${ic}</span><div><h3>${label}${label.endsWith('s')?'':'s'}</h3><small>${list.length} élément${list.length>1?'s':''}</small></div><button data-add="${type}">+</button></div>${list.length?`<div class="health-items">${list.slice(0,3).map(i=>`<button data-item="${i.id}"><span>${esc(i.title)}</span><small>${esc(i.time||'Sans heure')}</small><b>›</b></button>`).join('')}</div>`:`<div class="card-empty">Aucune donnée enregistrée</div>`}</article>`}).join('')}</div></section>`}
function wellbeingPage(){return `<section class="module-page"><div class="page-title"><div><h2>Bien-être</h2><p>Complète tes indicateurs du jour.</p></div></div><div class="wellbeing-list">${[['sleep','🌙','Sommeil','7 h 30'],['water','💧','Hydratation','1,8 L'],['activity','🏃','Activité','6 200 pas']].map(([id,ic,label,ex])=>`<button class="wellbeing-row" data-metric="${id}"><span class="wellbeing-icon">${ic}</span><div><h3>${label}</h3><p>${esc(state.metrics[id]||'Aucune donnée')}</p></div><span class="wellbeing-cta">${state.metrics[id]?'Modifier':'Ajouter'} ›</span></button>`).join('')}</div></section>`}
function colibriPage(){return `<section class="module-page colibri-page"><div class="page-title"><div><h2>Colibri</h2><p>Ton espace de questions. Les réponses IA viendront dans une étape dédiée.</p></div></div><div class="chat-list">${state.chat.length?state.chat.map(m=>`<div class="chat-bubble user">${esc(m.text)}</div>`).join(''):`<div class="empty"><div class="empty-icon"><img src="hummingbird-clean.png" alt=""></div><h3>Bonjour ${esc(state.profile.firstName||'')}</h3><p>Pose une question pour commencer ton historique.</p></div>`}</div><div class="chat-compose"><input id="chatInput" placeholder="Écris ta question..."><button data-chat-send>Envoyer</button></div></section>`}
function profilePage(){return `<section class="module-page"><h2>Profil</h2><p>Bienvenue ${esc(state.profile.firstName)}</p><div class="settings"><button data-edit-name><span>Prénom</span><b>${esc(state.profile.firstName)}</b></button><button data-reset class="danger"><span>Réinitialiser l’application</span><span>›</span></button></div></section>`}
function renderShell(page='home'){currentPage=page;const content=page==='home'?home():page==='profile'?profilePage():page==='health'?healthPage():page==='wellbeing'?wellbeingPage():colibriPage();app.innerHTML=`<div class="shell">${content}<button class="fab" data-open-add aria-label="Ajouter">+</button><nav>${[['home','⌂','Accueil'],['health','♡','Ma santé'],['wellbeing','◡','Bien-être'],['colibri','🐦','Colibri'],['profile','♙','Profil']].map(([id,ic,l])=>`<button data-page="${id}" class="${id===page?'active':''}">${ic}<small>${l}</small></button>`).join('')}</nav></div>`;bindShell()}
function bindShell(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>renderShell(b.dataset.page));document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>openForm(b.dataset.add));const openAdd=document.querySelector('[data-open-add]');if(openAdd)openAdd.onclick=openAddMenu;document.querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>openMetric(b.dataset.metric));document.querySelectorAll('[data-item]').forEach(b=>b.onclick=()=>openItemDetail(Number(b.dataset.item)));const chatSend=document.querySelector('[data-chat-send]');if(chatSend)chatSend.onclick=()=>{const input=document.querySelector('#chatInput'),q=input.value.trim();if(!q)return toast('Écris une question');state.chat.push({id:Date.now(),text:q});save();renderShell('colibri');toast('Question enregistrée')};const dismiss=document.querySelector('[data-dismiss-focus]');if(dismiss)dismiss.onclick=()=>{state.focusDismissed=true;save();renderShell('home')};const send=document.querySelector('[data-send-colibri]');if(send)send.onclick=()=>{const q=document.querySelector('#askColibri').value.trim();if(!q)return toast('Écris une question');state.chat.push({id:Date.now(),text:q});save();renderShell('colibri');toast('Question enregistrée')};const customize=document.querySelector('[data-customize]');if(customize)customize.onclick=()=>toast('Les actions seront personnalisables prochainement');const notifications=document.querySelector('[data-notifications]');if(notifications)notifications.onclick=()=>toast('Aucune nouvelle notification');const editName=document.querySelector('[data-edit-name]');if(editName)editName.onclick=()=>{const n=prompt('Ton prénom',state.profile.firstName);if(n&&n.trim()){state.profile.firstName=n.trim();save();renderShell('profile')}};const reset=document.querySelector('[data-reset]');if(reset)reset.onclick=()=>{if(confirm('Tout effacer ?')){localStorage.removeItem(STORAGE_KEY);state=structuredClone(defaultState);step=0;onboarding()}}}
function sheet(title,body){const d=document.createElement('div');d.className='modal-backdrop';d.innerHTML=`<div class="sheet"><div class="sheet-handle"></div><div class="sheet-head"><h2>${title}</h2><button data-close>×</button></div>${body}</div>`;document.body.appendChild(d);d.onclick=e=>{if(e.target===d)d.remove()};d.querySelector('[data-close]').onclick=()=>d.remove();return d}
function openAddMenu(){const d=sheet('Ajouter',`<div class="add-menu">${Object.entries(typeMeta).map(([id,[ic,l]])=>`<button data-menu-add="${id}"><span>${ic}</span>${l}</button>`).join('')}</div>`);d.querySelectorAll('[data-menu-add]').forEach(b=>b.onclick=()=>{d.remove();openForm(b.dataset.menuAdd)})}
function openForm(type){const [,label]=typeMeta[type];const d=sheet(`Ajouter : ${label}`,`<form id="itemForm"><label>Titre</label><input name="title" required placeholder="${label}"><label>Heure</label><input name="time" type="time"><label>Détails</label><textarea name="details" placeholder="Informations facultatives"></textarea><button class="save">Enregistrer</button></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),title=fd.get('title').trim();if(!title)return;state.items.push({id:Date.now(),type,title,time:fd.get('time'),details:fd.get('details')});save();d.remove();renderShell('home');toast(`${label} ajouté`)} }
function openItemDetail(id){const item=state.items.find(i=>i.id===id);if(!item)return;const [,label]=typeMeta[item.type];const d=sheet(label,`<div class="detail-card"><h3>${esc(item.title)}</h3><p><b>Heure :</b> ${esc(item.time||'Non renseignée')}</p>${item.details?`<p>${esc(item.details)}</p>`:''}<div class="detail-actions"><button data-edit>Modifier</button><button class="delete" data-delete>Supprimer</button></div></div>`);d.querySelector('[data-delete]').onclick=()=>{if(confirm('Supprimer cet élément ?')){state.items=state.items.filter(i=>i.id!==id);save();d.remove();renderShell(currentPage);toast('Élément supprimé')}};d.querySelector('[data-edit]').onclick=()=>{d.remove();openEditForm(item)}}
function openEditForm(item){const [,label]=typeMeta[item.type];const d=sheet(`Modifier : ${label}`,`<form id="itemEditForm"><label>Titre</label><input name="title" required value="${esc(item.title)}"><label>Heure</label><input name="time" type="time" value="${esc(item.time||'')}"><label>Détails</label><textarea name="details">${esc(item.details||'')}</textarea><button class="save">Enregistrer</button></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target);item.title=fd.get('title').trim();item.time=fd.get('time');item.details=fd.get('details');save();d.remove();renderShell(currentPage);toast('Modification enregistrée')}}
function openMetric(id){const labels={sleep:['Sommeil','ex. 7 h 30'],water:['Hydratation','ex. 1,8 L'],activity:['Activité','ex. 6 200 pas']};const [l,p]=labels[id],d=sheet(`Renseigner : ${l}`,`<form id="metricForm"><label>Valeur du jour</label><input name="value" required placeholder="${p}"><button class="save">Enregistrer</button></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();state.metrics[id]=new FormData(e.target).get('value').trim();save();d.remove();renderShell('home');toast(`${l} mis à jour`)}}
if(state.onboardingComplete)renderShell('home');else onboarding();if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});

// Finition de l'accueil validé : illustration propre, navigation et clavier.
function polishNymia(){
  document.querySelectorAll('img[src="hummingbird-clean.png"]').forEach(img=>{img.src='hummingbird-clean.png';img.alt='Colibri Nymia'});
  const nav=document.querySelector('nav'),fab=document.querySelector('.fab');
  if(nav&&fab&&!nav.contains(fab)){fab.classList.add('nav-add');nav.insertBefore(fab,nav.querySelector('[data-page="wellbeing"]'))}
  const tab=nav?.querySelector('[data-page="colibri"]');
  if(tab&&!tab.querySelector('img'))tab.innerHTML='<img class="nav-colibri" src="hummingbird-transparent.png" alt=""><small>Colibri</small>';
  const start=document.querySelector('.focus-buttons .filled');
  if(start&&start.textContent.trim()==='Commencer')start.onclick=openAddMenu;
  document.querySelectorAll('[data-health-open]:not([data-bound])').forEach(button=>{
    button.dataset.bound='true';
    button.onclick=()=>{const type=button.dataset.healthOpen,list=state.items.filter(item=>item.type===type);if(list.length===1)openItemDetail(list[0].id);else openHealthList(type)};
  });
  const healthSearch=document.querySelector('#healthSearch');
  if(healthSearch&&!healthSearch.dataset.bound){healthSearch.dataset.bound='true';healthSearch.oninput=()=>{const query=healthSearch.value.trim().toLocaleLowerCase('fr');document.querySelectorAll('[data-health-section]').forEach(card=>card.hidden=query&&!card.textContent.toLocaleLowerCase('fr').includes(query))}}
  const emergency=document.querySelector('[data-health-emergency]');
  if(emergency&&!emergency.dataset.bound){emergency.dataset.bound='true';emergency.onclick=()=>openForm('emergency')}
}
new MutationObserver(polishNymia).observe(app,{childList:true,subtree:true});
polishNymia();
if(window.visualViewport){const syncKeyboard=()=>document.body.classList.toggle('keyboard-open',window.visualViewport.height<window.innerHeight*.78);window.visualViewport.addEventListener('resize',syncKeyboard)}

Object.assign(typeMeta,{analysis:['🧪','Analyse'],vaccine:['✚','Vaccin'],allergy:['◇','Allergie'],history:['◷','Antécédent'],professional:['⚕','Professionnel'],constant:['⌁','Constante'],emergency:['!','Information d’urgence']});
const healthSections=[['treatment','Traitements','Tes médicaments et leurs rappels','pill'],['appointment','Rendez-vous','Tes consultations à venir','calendar'],['symptom','Symptômes','Note ce que tu ressens','heart'],['analysis','Analyses','Résultats et bilans biologiques','flask'],['document','Documents','Ordonnances et comptes rendus','document'],['constant','Constantes','Poids, tension, glycémie…','pulse'],['vaccine','Vaccins','Ton calendrier vaccinal','shield'],['allergy','Allergies','Médicaments, aliments et autres','allergy'],['history','Antécédents','Ton historique médical','history'],['professional','Professionnels','Médecins et spécialistes','doctor']];
function healthIcon(name){const icons={pill:'M9 4a5 5 0 0 1 7 7l-5 5a5 5 0 0 1-7-7l5-5Zm-2 9 6-6',calendar:'M5 7h14v12H5zM8 4v5m8-5v5M5 11h14',heart:'M12 20S4 15 4 9a4 4 0 0 1 7-3l1 1 1-1a4 4 0 0 1 7 3c0 6-8 11-8 11Z',flask:'M9 3h6m-5 0v6l-5 9a2 2 0 0 0 2 3h10a2 2 0 0 0 2-3l-5-9V3M7 16h10',document:'M7 3h7l4 4v14H7zM14 3v5h5M10 13h5m-5 4h5',pulse:'M3 12h4l2-5 4 10 2-5h6',shield:'M12 3l7 3v5c0 5-3 8-7 10-4-2-7-5-7-10V6zM9 12h6m-3-3v6',allergy:'M12 4v16M7 7l10 10M17 7 7 17',history:'M4 12a8 8 0 1 0 2-5M4 4v5h5M12 8v5l3 2',doctor:'M8 4v5a4 4 0 0 0 8 0V4M12 13v7m0 0h5a3 3 0 0 0 3-3v-2'};return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]}"/></svg>`}
function healthPage(){const total=state.items.filter(item=>healthSections.some(([type])=>type===item.type)).length,appointments=state.items.filter(item=>item.type==='appointment').length,treatments=state.items.filter(item=>item.type==='treatment').length;return `<section class="health-page"><header class="health-header"><div><span class="eyebrow">MON ESPACE</span><h1>Ma santé</h1><p>Tout ton suivi, simplement au même endroit.</p></div><button class="health-header-add" data-open-add aria-label="Ajouter une information">+</button></header><label class="health-search"><span>⌕</span><input id="healthSearch" type="search" placeholder="Rechercher dans ma santé"></label><div class="health-overview"><article><span>À venir</span><b>${appointments}</b><small>rendez-vous</small></article><article><span>En cours</span><b>${treatments}</b><small>traitements</small></article><article><span>Dossier</span><b>${total}</b><small>éléments</small></article></div><div class="health-section-title"><div><span>✦</span><h2>Mon suivi</h2></div><button data-open-add>Ajouter</button></div><div class="health-dashboard">${healthSections.slice(0,6).map(([type,title,description,icon])=>healthDashboardCard(type,title,description,icon)).join('')}</div><div class="health-section-title"><div><span>⌘</span><h2>Mon dossier médical</h2></div></div><div class="medical-record">${healthSections.slice(6).map(([type,title,description,icon])=>healthRecordRow(type,title,description,icon)).join('')}</div><button class="emergency-card" type="button" data-health-emergency><span class="emergency-icon">!</span><span><b>Informations d’urgence</b><small>Contacts, groupe sanguin et informations essentielles</small></span><span>›</span></button></section>`}
function healthDashboardCard(type,title,description,icon){const list=state.items.filter(item=>item.type===type);return `<article class="health-dashboard-card" data-health-section="${type}"><button class="health-main-action" data-health-open="${type}"><span class="health-svg ${type}">${healthIcon(icon)}</span><span class="health-card-copy"><b>${title}</b><small>${list.length?`${list.length} élément${list.length>1?'s':''}`:description}</small></span><span class="health-chevron">›</span></button><button class="health-inline-add" data-add="${type}" aria-label="Ajouter : ${title}">+</button></article>`}
function healthRecordRow(type,title,description,icon){const list=state.items.filter(item=>item.type===type);return `<article class="medical-row" data-health-section="${type}"><button data-health-open="${type}"><span class="health-svg ${type}">${healthIcon(icon)}</span><span><b>${title}</b><small>${list.length?`${list.length} enregistré${list.length>1?'s':''}`:description}</small></span><span>›</span></button><button class="record-add" data-add="${type}" aria-label="Ajouter : ${title}">+</button></article>`}
function openHealthList(type){const [,label]=typeMeta[type],list=state.items.filter(item=>item.type===type);const d=sheet(label,`${list.length?`<div class="health-sheet-list">${list.map(item=>`<button data-sheet-item="${item.id}"><span><b>${esc(item.title)}</b><small>${esc(item.time||'Sans horaire')}</small></span><span>›</span></button>`).join('')}</div>`:'<div class="sheet-empty"><b>Aucune donnée pour le moment</b><p>Ajoute ta première information quand tu le souhaites.</p></div>'}<button class="save" data-sheet-add>Ajouter</button>`);d.querySelectorAll('[data-sheet-item]').forEach(button=>button.onclick=()=>{d.remove();openItemDetail(Number(button.dataset.sheetItem))});d.querySelector('[data-sheet-add]').onclick=()=>{d.remove();openForm(type)}}
