const screens=[...document.querySelectorAll('.screen')],nav=document.getElementById('bottomNav'),toast=document.getElementById('toast'),sheet=document.getElementById('sheet'),modal=document.getElementById('modal'),form=document.getElementById('entryForm');
const state=JSON.parse(localStorage.getItem('nymia-empty-v1')||'{"profile":{},"entries":[]}');let currentType='';
const labels={appointment:'Rendez-vous',treatment:'Traitement',symptom:'Symptôme',note:'Note',meal:'Repas',exam:'Examen',measurement:'Mesure',cycle:'Santé féminine',activity:'Activité',meditation:'Méditation',sleep:'Sommeil',water:'Hydratation'};
function save(){localStorage.setItem('nymia-empty-v1',JSON.stringify(state));render()}
function showScreen(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));const main=['home','health','wellbeing','colibri','journal','profile'];nav.style.display=main.includes(name)?'flex':'none';document.querySelector('.floating-add').style.display=main.includes(name)?'block':'none';document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo(0,0)}
function notify(t){toast.textContent=t;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function fields(type){if(type==='profile')return `<label>Prénom</label><input name="name" value="${esc(state.profile.name||'')}" required><label>Phrase de profil</label><input name="subtitle" value="${esc(state.profile.subtitle||'')}">`;if(type==='appointment')return `<label>Titre</label><input name="title" placeholder="Ex. Consultation gynécologue" required><label>Date</label><input name="date" type="date" required><label>Heure</label><input name="time" type="time"><label>Lieu</label><input name="detail" placeholder="Lieu ou professionnel">`;if(type==='treatment')return `<label>Nom du traitement</label><input name="title" required><label>Posologie</label><input name="detail" placeholder="Ex. 1 comprimé le matin"><label>Prochaine prise</label><input name="time" type="time">`;if(type==='note')return `<label>Titre</label><input name="title" required><label>Texte</label><textarea name="detail"></textarea>`;if(type==='water')return `<label>Quantité en litres</label><input name="value" type="number" min="0" step="0.1" required>`;if(type==='sleep')return `<label>Nombre d'heures</label><input name="value" type="number" min="0" step="0.25" required>`;if(type==='activity')return `<label>Nombre de pas</label><input name="value" type="number" min="0" step="1" required>`;return `<label>${labels[type]||'Titre'}</label><input name="title" required><label>Détails</label><textarea name="detail"></textarea>`}
function openForm(type){currentType=type;sheet.classList.remove('show');document.getElementById('formTitle').textContent=type==='profile'?'Modifier mon profil':'Ajouter : '+(labels[type]||type);document.getElementById('formFields').innerHTML=fields(type);modal.classList.add('show')}
form.addEventListener('submit',e=>{e.preventDefault();const d=Object.fromEntries(new FormData(form));if(currentType==='profile')state.profile=d;else state.entries.push({id:Date.now(),type:currentType,...d,created:new Date().toISOString()});modal.classList.remove('show');form.reset();save();notify('Enregistré')});
function render(){const name=state.profile.name||'Nymia';['homeName','chatName','profileName'].forEach(id=>document.getElementById(id).textContent=name);document.getElementById('profileSubtitle').textContent=state.profile.subtitle||'Complète ton profil pour personnaliser l’application.';const fmt=new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());document.getElementById('todayDate').textContent=fmt.charAt(0).toUpperCase()+fmt.slice(1);
const count=t=>state.entries.filter(e=>e.type===t).length;document.getElementById('symptomCount').textContent=count('symptom');document.getElementById('treatmentCount').textContent=count('treatment');document.getElementById('examCount').textContent=count('exam');document.getElementById('documentCount').textContent=count('document');
const latest=t=>[...state.entries].reverse().find(e=>e.type===t);const water=latest('water'),sleep=latest('sleep'),activity=latest('activity');document.getElementById('homeWater').textContent=water?water.value+' L':'—';document.getElementById('waterMetric').textContent=water?water.value:'—';document.getElementById('homeSleep').textContent=sleep?sleep.value+' h':'—';document.getElementById('sleepMetric').textContent=sleep?sleep.value:'—';document.getElementById('homeSteps').textContent=activity?Number(activity.value).toLocaleString('fr-FR')+' pas':'—';document.getElementById('stepsMetric').textContent=activity?Number(activity.value).toLocaleString('fr-FR'):'—';document.getElementById('mealMetric').textContent=count('meal')||'—';
const appts=state.entries.filter(e=>e.type==='appointment').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));document.getElementById('healthToday').innerHTML=appts.length?card(appts[0]):`<b>Aucun rendez-vous</b><span>Ajoute ton prochain rendez-vous.</span>`;
const today=new Date().toISOString().slice(0,10),agenda=state.entries.filter(e=>e.date===today||['treatment','meal','meditation'].includes(e.type));document.getElementById('agendaList').innerHTML=agenda.length?agenda.map(card).join(''):`<div class="empty-state"><b>Rien de prévu aujourd’hui</b><span>Ajoute tes rendez-vous, traitements ou activités.</span></div>`;
const tr=state.entries.filter(e=>e.type==='treatment');document.getElementById('treatmentList').innerHTML=tr.length?tr.map(card).join(''):`<div class="empty-state"><b>Aucun traitement</b><span>Ajoute tes traitements et tes rappels.</span></div>`;
const notes=state.entries.filter(e=>e.type==='note').reverse();document.getElementById('notesList').innerHTML=notes.length?notes.map(card).join(''):`<b>Aucune note</b><span>Écris ta première note personnelle.</span>`;
const next=appts[0];document.getElementById('focusTitle').textContent=next?(next.title||'Rendez-vous')+(next.time?' à '+next.time:''):'Tout est prêt.';document.getElementById('focusText').textContent=next?(next.detail||'Ton prochain rendez-vous est enregistré.'):'Ajoute un rendez-vous, un traitement ou une note pour commencer.'}
function card(e){return `<div class="saved-card"><span><b>${esc(e.title||labels[e.type]||'Élément')}</b><small>${esc([e.date,e.time,e.detail,e.value].filter(Boolean).join(' · '))}</small></span><button class="delete-mini" data-delete="${e.id}">×</button></div>`}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n){showScreen(n.dataset.nav);return}const a=e.target.closest('[data-add]');if(a){openForm(a.dataset.add);return}const del=e.target.closest('[data-delete]');if(del){state.entries=state.entries.filter(x=>x.id!=del.dataset.delete);save();return}const act=e.target.closest('[data-action]')?.dataset.action;if(!act)return;if(act==='open-add')sheet.classList.add('show');else if(act==='close-sheet')sheet.classList.remove('show');else if(act==='close-modal')modal.classList.remove('show');else if(act==='edit-profile')openForm('profile');else if(act==='document')document.getElementById('galleryInput').click();else if(act==='send-question'){const q=document.getElementById('quickQuestion').value.trim();if(q){showScreen('colibri');document.getElementById('chatInput').value=q;sendChat()}}else if(act==='chat-send')sendChat();else if(act==='export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),x=document.createElement('a');x.href=u;x.download='nymia-donnees.json';x.click();URL.revokeObjectURL(u)}else notify('Fonction disponible prochainement')});
function sendChat(){const i=document.getElementById('chatInput'),t=i.value.trim();if(!t)return;const area=document.getElementById('chatArea');area.insertAdjacentHTML('beforeend',`<div class="message user"><p>${esc(t)}</p></div>`);i.value='';setTimeout(()=>{area.insertAdjacentHTML('beforeend','<div class="message bot"><span>🐦</span><p>J’ai bien reçu ta demande. Ton espace reste privé et se remplit uniquement avec les informations que tu ajoutes.</p></div>');area.scrollTop=area.scrollHeight},350)}
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>showScreen('home')));document.getElementById('shutter').onclick=()=>document.getElementById('cameraInput').click();['cameraInput','galleryInput'].forEach(id=>document.getElementById(id).addEventListener('change',e=>{if(!e.target.files?.length)return;state.entries.push({id:Date.now(),type:'document',title:e.target.files[0].name,detail:'Document importé'});save();showScreen('analysis');setTimeout(()=>showScreen('scanresult'),1600)}));render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
